#data_base made by GPT :/
data_base = [
    ('good', 'good'),
    ('bad', 'bad'),
    ('I woke up early, exercised, and had a productive day', 'good'),
    ('I stayed up late, struggled to get out of bed, and felt tired all day', 'bad'),
    ('I had a great lunch with friends and enjoyed the sunny weather', 'good'),
    ('My car broke down, and I was late for work', 'bad'),
    ('I finished a project ahead of schedule and felt accomplished', 'good'),
    ('I received negative feedback at work, and it affected my mood', 'bad'),
    ('I went hiking and enjoyed the beautiful scenery', 'good'),
    ('I spilled coffee on my shirt and felt embarrassed', 'bad'),
    ('I had a wonderful date and felt butterflies', 'good'),
    ('I forgot an important meeting and felt unprofessional', 'bad'),
    ('I volunteered at a shelter and felt fulfilled', 'good'),
    ('I missed my bus and had to wait in the rain', 'bad'),
    ('I learned a new skill and felt proud of myself', 'good'),
    ('I encountered a difficult task and felt overwhelmed', 'bad'),
    ('I had a relaxing spa day and felt rejuvenated', 'good'),
    ('I had a headache all day and couldn’t concentrate', 'bad'),
    ('I watched a great movie and had a fun night in', 'good'),
    ('I got stuck in traffic and was frustrated', 'bad'),
    ('I baked cookies and shared them with my neighbors', 'good'),
    ('I made a mistake at work and felt embarrassed', 'bad'),
    ('I attended a concert and had an amazing time', 'good'),
    ('I felt lonely and didn’t reach out to anyone', 'bad'),
    ('I celebrated a friend’s birthday and enjoyed the festivities', 'good'),
    ('I had an argument with a family member and felt upset', 'bad'),
    ('I took a day off to relax and it was refreshing', 'good'),
    ('I felt anxious about a presentation and couldn’t sleep', 'bad'),
    ('I found a great book and couldn’t put it down', 'good'),
    ('I had to deal with a rude customer and felt drained', 'bad'),
    ('I joined a new club and met great people', 'good'),
    ('I lost my wallet and felt stressed', 'bad'),
    ('I helped a coworker and felt appreciated', 'good'),
    ('I didn’t get enough sleep and was tired all day', 'bad'),
    ('I participated in a community event and felt proud', 'good'),
    ('I felt insecure about my appearance and avoided socializing', 'bad'),
    ('I cooked a delicious dinner and enjoyed it with family', 'good'),
    ('I struggled with my workload and felt discouraged', 'bad'),
    ('I received a compliment that made my day', 'good'),
    ('I had a rough morning and spilled my breakfast', 'bad'),
    ('I took a beautiful photo and shared it online', 'good'),
    ('I missed an important call and felt anxious', 'bad'),
    ('I spent the day at the beach and felt relaxed', 'good'),
    ('I forgot to take my medication and felt off', 'bad'),
    ('I received a promotion and celebrated with friends', 'good'),
    ('I had to cancel plans last minute and felt guilty', 'bad'),
    ('I completed a challenging workout and felt strong', 'good'),
    ('I felt like I was in a rut and didn’t know how to change', 'bad'),
    ('I tried a new restaurant and loved the food', 'good'),
    ('I had a bad day at work and felt unmotivated', 'bad'),
    ('I painted a picture and felt creative', 'good'),
    ('I faced unexpected expenses and felt worried', 'bad'),
    ('I discovered a new hobby and felt excited', 'good'),
    ('I felt overwhelmed by my responsibilities and needed a break', 'bad'),
    ('I got a good night’s sleep and felt refreshed', 'good'),
    ('I made a mistake while cooking and it ruined dinner', 'bad'),
    ('I attended a workshop and learned valuable skills', 'good'),
    ('I felt frustrated by technical issues during a meeting', 'bad'),
    ('I danced at a party and felt free', 'good'),
    ('I felt out of place at a gathering and wanted to leave', 'bad'),
    ('I found a new favorite song and listened to it all day', 'good'),
    ('I had a rough conversation with a colleague and felt drained', 'bad'),
    ('I made plans for the weekend and felt excited', 'good'),
    ('I felt neglected by friends and it hurt', 'bad'),
    ('I tried a new recipe and it turned out great', 'good'),
    ('I felt guilty for not being productive enough', 'bad'),
    ('I got a positive review from my manager and felt proud', 'good'),
    ('I struggled to meet a deadline and felt anxious', 'bad'),
    ('I went for a run and enjoyed the fresh air', 'good'),
    ('I felt disorganized and couldn’t focus', 'bad'),
    ('I celebrated a milestone with friends and felt happy', 'good'),
    ('I received a bill I wasn’t expecting and felt stressed', 'bad'),
    ('I explored a new city and loved every moment', 'good'),
    ('I felt overwhelmed by negative news and needed a break', 'bad'),
    ('I watched the sunset and felt at peace', 'good'),
    ('I had a hard time waking up and felt groggy', 'bad')
]