#data_base made by GPT :/
data_base = [
    ("I woke up early, exercised, and had a productive day", "good"),
    ("I stayed up late, struggled to get out of bed, and felt tired all day", "bad"),
    ("I had a great lunch with friends and enjoyed the sunny weather", "good"),
    ("My car broke down, and I was late for work", "bad"),
    ("I finished a project ahead of schedule and felt accomplished", "good"),
    ("I received negative feedback at work, and it affected my mood", "bad"),
    ("I went hiking and enjoyed the beautiful scenery", "good"),
    ("I spilled coffee on my shirt and felt embarrassed", "bad"),
    ("I had a wonderful date and felt butterflies", "good"),
    ("I forgot an important meeting and felt unprofessional", "bad"),
    ("I volunteered at a shelter and felt fulfilled", "good"),
    ("I missed my bus and had to wait in the rain", "bad"),
    ("I learned a new skill and felt proud of myself", "good"),
    ("I encountered a difficult task and felt overwhelmed", "bad"),
    ("I had a relaxing spa day and felt rejuvenated", "good"),
    ("I had a headache all day and couldn’t concentrate", "bad"),
    ("I watched a great movie and had a fun night in", "good"),
    ("I got stuck in traffic and was frustrated", "bad"),
    ("I baked cookies and shared them with my neighbors", "good"),
    ("I made a mistake at work and felt embarrassed", "bad"),
    ("I attended a concert and had an amazing time", "good"),
    ("I felt lonely and didn’t reach out to anyone", "bad"),
    ("I celebrated a friend’s birthday and enjoyed the festivities", "good"),
    ("I had an argument with a family member and felt upset", "bad"),
    ("I took a day off to relax and it was refreshing", "good"),
    ("I felt anxious about a presentation and couldn’t sleep", "bad"),
    ("I found a great book and couldn’t put it down", "good"),
    ("I had to deal with a rude customer and felt drained", "bad"),
    ("I joined a new club and met great people", "good"),
    ("I lost my wallet and felt stressed", "bad"),
    ("I helped a coworker and felt appreciated", "good"),
    ("I didn’t get enough sleep and was tired all day", "bad"),
    ("I participated in a community event and felt proud", "good"),
    ("I felt insecure about my appearance and avoided socializing", "bad"),
    ("I cooked a delicious dinner and enjoyed it with family", "good"),
    ("I struggled with my workload and felt discouraged", "bad"),
    ("I received a compliment that made my day", "good"),
    ("I had a rough morning and spilled my breakfast", "bad"),
    ("I took a beautiful photo and shared it online", "good"),
    ("I missed an important call and felt anxious", "bad"),
    ("I spent the day at the beach and felt relaxed", "good"),
    ("I forgot to take my medication and felt off", "bad"),
    ("I received a promotion and celebrated with friends", "good"),
    ("I had to cancel plans last minute and felt guilty", "bad"),
    ("I completed a challenging workout and felt strong", "good"),
    ("I felt like I was in a rut and didn’t know how to change", "bad"),
    ("I tried a new restaurant and loved the food", "good"),
    ("I had a bad day at work and felt unmotivated", "bad"),
    ("I painted a picture and felt creative", "good"),
    ("I faced unexpected expenses and felt worried", "bad"),
    ("I discovered a new hobby and felt excited", "good"),
    ("I felt overwhelmed by my responsibilities and needed a break", "bad"),
    ("I got a good night’s sleep and felt refreshed", "good"),
    ("I made a mistake while cooking and it ruined dinner", "bad"),
    ("I attended a workshop and learned valuable skills", "good"),
    ("I felt frustrated by technical issues during a meeting", "bad"),
    ("I danced at a party and felt free", "good"),
    ("I felt out of place at a gathering and wanted to leave", "bad"),
    ("I found a new favorite song and listened to it all day", "good"),
    ("I had a rough conversation with a colleague and felt drained", "bad"),
    ("I made plans for the weekend and felt excited", "good"),
    ("I felt neglected by friends and it hurt", "bad"),
    ("I tried a new recipe and it turned out great", "good"),
    ("I felt guilty for not being productive enough", "bad"),
    ("I got a positive review from my manager and felt proud", "good"),
    ("I struggled to meet a deadline and felt anxious", "bad"),
    ("I went for a run and enjoyed the fresh air", "good"),
    ("I felt disorganized and couldn’t focus", "bad"),
    ("I celebrated a milestone with friends and felt happy", "good"),
    ("I received a bill I wasn’t expecting and felt stressed", "bad"),
    ("I explored a new city and loved every moment", "good"),
    ("I felt overwhelmed by negative news and needed a break", "bad"),
    ("I watched the sunset and felt at peace", "good"),
    ("I had a hard time waking up and felt groggy", "bad"),
    ("I had a quiet morning, made some tea, and worked on a hobby", "good"),
    ("My alarm didn’t go off, I was late for everything, and felt rushed", "bad"),
    ("Took a walk in the rain, enjoyed the fresh air, and felt relaxed", "good"),
    ("I spilled coffee on my clothes, missed the bus, and was late for work", "bad"),
    ("Spent the day with family, played board games, and had a great time", "good"),
    ("Had to deal with some last-minute changes at work, felt stressed", "bad"),
    ("Woke up early, had a peaceful breakfast, and went for a morning jog", "good"),
    ("Dealt with a lot of paperwork, it was tedious and frustrating", "bad"),
    ("Had a lovely lunch with colleagues, chatted and laughed a lot", "good"),
    (
        "Had a huge project deadline, worked late into the night, and felt exhausted",
        "bad",
    ),
    ("Finished a project I’ve been working on for weeks, felt accomplished", "good"),
    ("Missed an important call, felt disappointed and stressed", "bad"),
    ("Had a slow start but ended up having a productive afternoon", "good"),
    ("Spent most of the day in bed, feeling sick and tired", "bad"),
    ("Made progress on my fitness goals, felt strong and motivated", "good"),
    ("Got stuck in an endless meeting, felt like nothing was being achieved", "bad"),
    ("Had a relaxing evening reading a book, felt calm and peaceful", "good"),
    ("Woke up feeling groggy, struggled to focus at work all day", "bad"),
    ("Went out with friends to a new restaurant, had an amazing meal", "good"),
    ("Had to cancel plans last minute, felt disappointed and frustrated", "bad"),
    ("Completed my to-do list for the day and felt very productive", "good"),
    ("Spent the whole day on calls, by the end I felt drained", "bad"),
    (
        "Had a very successful meeting with my boss, I’m excited about the next steps",
        "good",
    ),
    ("Dealt with a difficult client all day, felt frustrated and exhausted", "bad"),
    ("Took a break from social media, enjoyed a peaceful day offline", "good"),
    ("Got caught up in office drama, which made me feel uncomfortable", "bad"),
    ("Visited a museum, learned something new, and had a great time", "good"),
    ("Had a terrible headache, couldn’t focus on anything", "bad"),
    ("Spent time volunteering, felt really good about giving back", "good"),
    ("The internet was down all day, which made work difficult", "bad"),
    ("Did a deep clean of the house, felt productive and satisfied", "good"),
    ("My car broke down, spent the day waiting for repairs", "bad"),
    ("Had a peaceful day meditating, felt calm and centered", "good"),
    ("Had to juggle multiple tasks at once, felt overwhelmed", "bad"),
    ("Went for a run, enjoyed the outdoors, and felt energized", "good"),
    ("Felt anxious all day, struggled to calm my thoughts", "bad"),
    ("Had a smooth day at work, everything went according to plan", "good"),
    ("Faced multiple setbacks, felt like I was going nowhere", "bad"),
    ("Caught up on sleep, felt refreshed and ready to take on the day", "good"),
    ("Had a frustrating encounter with a customer, left me feeling annoyed", "bad"),
    ("Spent time organizing my workspace, felt productive and clear-minded", "good"),
    ("Wasted the entire afternoon procrastinating, felt guilty", "bad"),
    ("Had a nice evening with a friend, shared lots of good memories", "good"),
    ("Spent the day in traffic, couldn’t get anything done", "bad"),
    ("Had a great workout at the gym, felt strong and accomplished", "good"),
    (
        "Had a minor argument with a coworker, spent the rest of the day feeling tense",
        "bad",
    ),
    ("Enjoyed a quiet afternoon in the park, felt peaceful", "good"),
    ("Had to rush to meet a deadline, didn’t manage to finish on time", "bad"),
    ("Had a lovely morning at a café, felt productive and inspired", "good"),
    ("Spent most of the day solving problems, felt mentally drained", "bad"),
    ("Made a delicious dinner, tried a new recipe, and felt proud", "good"),
    ("Spent hours on the phone with customer service, which was frustrating", "bad"),
    ("Had a great team meeting, felt appreciated by my colleagues", "good"),
    ("Was stuck in a long meeting, didn’t feel like it was productive", "bad"),
    ("Went hiking with friends, had an adventurous and fun day", "good"),
    ("Missed an important appointment, which caused a lot of stress", "bad"),
    ("Took some time for self-care, had a bubble bath, and felt recharged", "good"),
    ("My laptop crashed and I lost all my work, felt devastated", "bad"),
    ("Had an awesome afternoon working on creative projects, felt inspired", "good"),
    ("Spent the whole day answering emails, it was overwhelming", "bad"),
    ("Took a spontaneous trip to the beach, felt free and happy", "good"),
    ("Dealt with a lot of paperwork, nothing seemed to go right", "bad"),
    ("Tried a new workout class, felt challenged and energized", "good"),
    ("Had an argument with a close friend, felt upset the entire day", "bad"),
    ("Worked on a personal project, made great progress and felt accomplished", "good"),
    ("Had a very hectic day with too many distractions, felt unfocused", "bad"),
    ("Got to enjoy a nice dinner with my family, had meaningful conversations", "good"),
    ("Had an issue with a colleague, didn’t feel supported at all", "bad"),
    ("Went to a yoga class, felt stretched and centered", "good"),
    ("Spent the entire day working on a single task, but couldn’t complete it", "bad"),
    ("Had a productive day with lots of small wins, felt successful", "good"),
    ("Got into a disagreement with a family member, felt frustrated all day", "bad"),
    ("Had a fantastic day shopping for new clothes, felt refreshed", "good"),
    ("Woke up feeling anxious, struggled to get anything done", "bad"),
    ("Had a nice picnic with friends, enjoyed the sunshine", "good"),
    ("My day was ruined by a sudden downpour, couldn’t do anything outside", "bad"),
    ("Spent time with my partner, we had great conversations and laughs", "good"),
    ("Had to work on a weekend, felt unhappy about it", "bad"),
    ("Enjoyed a long walk with my dog, felt connected to nature", "good"),
    ("Was overwhelmed with work all day, didn’t get anything finished", "bad"),
    ("Had a great breakfast, felt ready to tackle the day", "good"),
    ("Spent too much time worrying about small details, which slowed me down", "bad"),
    ("Went to the spa for a relaxing massage, felt completely rejuvenated", "good"),
    ("Spent hours at the office, didn’t feel like I achieved anything", "bad"),
    ("Had a successful project launch, felt accomplished and proud", "good"),
    ("Had to handle an emergency at work, felt stressed and overwhelmed", "bad"),
    ("Enjoyed a quiet evening with a good book, felt relaxed", "good"),
    ("Had to take care of some unexpected chores, felt exhausted by the end", "bad"),
    ("Had a delicious brunch, spent quality time with friends", "good"),
    ("Had a frustrating experience with technology, couldn’t get anything done", "bad"),
    ("Spent the afternoon at a local market, enjoyed browsing and relaxing", "good"),
    ("Had a day full of interruptions, couldn’t focus on any one thing", "bad"),
    ("Spent the day learning a new skill, felt excited about the progress", "good"),
    ("Had to deal with multiple stressful situations, felt mentally drained", "bad"),
    ("Visited a friend I hadn’t seen in a while, had a great time catching up", "good"),
    ("Had a very stressful morning at work, everything felt overwhelming", "bad"),
    (
        "Had an enjoyable day in the city, explored new places and tried new food",
        "good",
    ),
    ("Felt behind all day, couldn’t catch up with anything", "bad"),
    ("Did some painting, it was very therapeutic and satisfying", "good"),
    ("Had a fight with my roommate, felt tense and uneasy the entire day", "bad"),
    ("Had an amazing day at the park, enjoyed a picnic and good company", "good"),
    ("Wasted too much time on distractions, couldn’t focus on work", "bad"),
    (
        "Had a productive morning, took a nice break, and continued working in the afternoon",
        "good",
    ),
    ("Dealt with a series of small problems all day, felt mentally exhausted", "bad"),
    (
        "Spent a lot of time thinking about my goals, felt motivated to push forward",
        "good",
    ),
    ("Had a slow day at work, didn’t accomplish much", "bad"),
    ("Tried a new workout routine, felt stronger and more confident", "good"),
    ("Had to reschedule everything, felt frustrated by all the changes", "bad"),
    ("Had a lovely afternoon enjoying the sunshine, felt at peace", "good"),
    ("Felt drained after a long day, needed some time to relax", "bad"),
    (
        "Had a day full of learning, made great progress in my personal development",
        "good",
    ),
    ("Had a frustrating conversation with a client, left me feeling drained", "bad"),
    ("Took a trip to the countryside, felt rejuvenated and refreshed", "good"),
    ("Struggled to finish a project, felt like I was going in circles", "bad"),
    ("Spent the day decluttering, felt proud of how much I accomplished", "good"),
    ("Had a tough day with many setbacks, felt like nothing was going right", "bad"),
    ("Had a peaceful day reading, felt content and at ease", "good"),
    ("Got into a disagreement with a friend, it affected my whole day", "bad"),
    ("Enjoyed a cozy evening at home with a good movie", "good"),
    ("Had a very hectic workday, felt mentally exhausted by the end", "bad"),
    ("Spent the day with my pets, felt loved and happy", "good"),
    ("Had an argument with a family member, felt frustrated all day", "bad"),
    ("Took a weekend trip, explored new places and had a great time", "good"),
    ("Had a slow and unproductive day, didn’t feel like doing anything", "bad"),
    ("Had a positive meeting with a mentor, felt encouraged and motivated", "good"),
    ("Spent the day stuck in traffic, didn’t accomplish anything", "bad"),
    ("Enjoyed a relaxing bath, listened to music, and felt completely relaxed", "good"),
    ("Had a chaotic day, couldn’t focus on any task for long", "bad"),
    ("I woke up early, exercised, and had a productive day", "good"),
    (
        "I got stuck in traffic, had a stressful meeting, but managed to finish work",
        "bad",
    ),
    ("Spent quality time with family, had a great dinner, and felt relaxed", "good"),
    ("Had a long day at work, dealing with lots of emails and issues", "bad"),
    (
        "Went for a walk in the park, met a friend, and had a lovely conversation",
        "good",
    ),
    ("I was feeling unmotivated, didn’t get much done, and felt drained", "bad"),
    ("Got to enjoy a sunny afternoon at the beach, felt very refreshed", "good"),
    ("Had a busy day, missed lunch, and was stuck in back-to-back meetings", "bad"),
    ("Had a creative burst, worked on a project I love, and felt fulfilled", "good"),
    (
        "Had a disagreement with a colleague, and spent the day feeling frustrated",
        "bad",
    ),
    (
        "Woke up to a beautiful morning, did some yoga, and tackled my to-do list",
        "good",
    ),
    ("Had a stressful presentation, but in the end, it went well", "good"),
    ("Had a rough start, but things got better by the afternoon", "good"),
    ("Felt sick all day and couldn’t get much done", "bad"),
    (
        "Went to the gym, enjoyed a healthy meal, and felt energized throughout the day",
        "good",
    ),
    ("Had a calm, quiet day at home, reading and resting", "good"),
    ("Dealt with technical issues all day and couldn’t focus", "bad"),
    (
        "Had an enjoyable day at work, received compliments, and felt appreciated",
        "good",
    ),
    ("Ran errands all day, but nothing went as planned, very frustrating", "bad"),
    (
        "Had a fantastic dinner with friends, laughed a lot, and had a great time",
        "good",
    ),
    ("Spent too much time on social media, felt unproductive and drained", "bad"),
    ("Took a day off work, went hiking, and enjoyed the outdoors", "good"),
    ("Everything seemed to go wrong today, just one of those days", "bad"),
    ("Got a lot of things done at work and even managed to leave early", "good"),
    ("Felt overwhelmed with tasks, couldn’t manage my time well", "bad"),
    (
        "Had a peaceful morning, accomplished a lot in the afternoon, and relaxed at night",
        "good",
    ),
    ("Had a stressful encounter with a stranger, which threw me off", "bad"),
    (
        "Did a deep cleaning at home, which left me feeling accomplished and happy",
        "good",
    ),
    (
        "Felt anxious all day, couldn’t focus, and had a hard time dealing with stress",
        "bad",
    ),
    ("Had a fun day trying new activities, learned something new and exciting", "good"),
    ("Stayed in bed all day feeling tired and unmotivated", "bad"),
    (
        "Made a lot of progress on personal projects, felt productive and positive",
        "good",
    ),
    ("Dealt with lots of unexpected problems, but eventually handled them", "good"),
    ("Had a rough morning, but the evening was calm and enjoyable", "good"),
    ("Got into a fight with a friend, spent the day feeling upset", "bad"),
    ("Woke up late, rushed through the day, and ended it feeling drained", "bad"),
    ("Spent the day volunteering and felt fulfilled by helping others", "good"),
    ("Everything seemed to go smoothly today, felt in control and positive", "good"),
    ("Had an exhausting day at work, nothing went according to plan", "bad"),
    ("Enjoyed a day off, caught up on sleep, and felt recharged", "good"),
    ("Lost track of time and had a chaotic day trying to catch up", "bad"),
    (
        "Started the day with a good breakfast, had productive meetings, and ended it relaxed",
        "good",
    ),
    ("Spent too much time on emails, didn’t get much done, felt frustrated", "bad"),
    ("Had a successful day with lots of tasks completed, felt accomplished", "good"),
    ("Woke up with a headache, worked through the day, but ended up exhausted", "bad"),
    ("Got through a difficult project, and felt a sense of achievement", "good"),
    ("Had an argument with a family member, and the day felt tense", "bad"),
    ("Went for a run, enjoyed the fresh air, and felt great", "good"),
    (
        "My computer crashed, and I lost important work, felt incredibly frustrated",
        "bad",
    ),
    ("Met some new people, had interesting conversations, and felt inspired", "good"),
    ("Got stuck in traffic, was late for everything, and felt stressed", "bad"),
    ("Enjoyed a quiet day in nature, it was very peaceful and calming", "good"),
    ("Had to deal with an unexpected emergency, which took up all my energy", "bad"),
    ("Took a yoga class, had a delicious smoothie, and felt energized", "good"),
    ("Had a slow day, didn’t accomplish much, and felt disappointed", "bad"),
    ("Had a successful meeting with clients, everyone was pleased", "good"),
    ("Couldn’t focus at work, had a lot of distractions and setbacks", "bad"),
    ("Had a fun and productive day with my team, great teamwork", "good"),
    ("Felt overwhelmed by responsibilities, couldn’t find time to relax", "bad"),
    ("Spent the day outdoors, went for a bike ride, and felt free", "good"),
    (
        "Didn’t get enough sleep, had a rough time staying awake throughout the day",
        "bad",
    ),
    ("Spent the day organizing my house, felt accomplished and relaxed", "good"),
    ("Had a difficult conversation with my boss, felt stressed afterward", "bad"),
    (
        "Went to a concert, had a great time, and was surrounded by positive energy",
        "good",
    ),
    ("Was caught in a series of minor inconveniences, felt irritated all day", "bad"),
    ("Had a peaceful day working from home, stayed on task and felt calm", "good"),
    ("I spent too much time worrying, didn’t focus enough on tasks", "bad"),
    ("Had a relaxing bath, watched my favorite show, and felt recharged", "good"),
    (
        "Had to deal with a complicated project, felt overwhelmed but made progress",
        "good",
    ),
    ("I felt lazy all day, didn’t feel like doing anything productive", "bad"),
    ("Caught up with an old friend, reminisced about good times", "good"),
    ("Had a very busy and demanding day, but it all worked out in the end", "good"),
    ("Had to reschedule multiple plans, felt frustrated by all the changes", "bad"),
    ("Took a walk in the evening, saw a beautiful sunset, and felt at peace", "good"),
    ("My car broke down, and I had to cancel my appointments", "bad"),
    ("Spent the day gardening, enjoyed being outside, and felt grounded", "good"),
    ("Had a frustrating encounter at work, didn’t feel heard or respected", "bad"),
    ("Had a great day getting things done, felt super productive", "good"),
    ("Had an exhausting meeting, nothing was resolved, and I felt drained", "bad"),
    ("Went on a road trip with friends, had an amazing time together", "good"),
    ("Missed an important deadline, felt overwhelmed and anxious", "bad"),
    ("Had an amazing lunch with a friend, shared lots of laughs", "good"),
    ("My internet was down all day, which slowed everything down", "bad"),
    ("Spent time reflecting on personal goals, felt motivated to keep going", "good"),
    ("Had a very busy morning, then spent the afternoon catching up", "good"),
    ("Was stuck in back-to-back meetings all day, felt mentally exhausted", "bad"),
    ("Tried a new recipe, it turned out great, and I felt proud", "good"),
    ("Had a tough conversation with my partner, which left me feeling drained", "bad"),
    ("Worked on a passion project, felt energized and creative", "good"),
    ("Spent hours on a task that ended up not working out, felt frustrated", "bad"),
    ("Treated myself to a spa day, felt completely relaxed and rejuvenated", "good"),
    ("Had a lot of work to do, but didn’t manage to finish anything", "bad"),
    ("Took the day off, relaxed with a book, and felt peaceful", "good"),
    ("Struggled with a difficult task all day, didn’t make much progress", "bad"),
    ("Had a wonderful walk with my dog, enjoyed the outdoors", "good"),
    ("Had a slow day at work, couldn’t focus or get anything done", "bad"),
    ("Enjoyed a nice coffee and read a book, felt calm and content", "good"),
    ("Had a long and unproductive day, felt like I was running in circles", "bad"),
    ("Had a chance to relax with family, spent the day laughing and bonding", "good"),
    ("Had a tough start to the day, but everything slowly improved", "good"),
    ("Had an unexpected setback, but still managed to keep going", "good"),
    ("Was stuck in a long queue, made me late for everything", "bad"),
    ("Had a really productive day at work, felt accomplished and positive", "good"),
    ("Dealt with some minor health issues, which made me feel uneasy", "bad"),
    ("Went to a great fitness class, felt strong and energized", "good"),
    ("Had a stressful morning, couldn’t calm down for the rest of the day", "bad"),
    ("Spent the day doing nothing, felt really lazy", "bad"),
    ("Took the time to plan out my goals, felt motivated to achieve them", "good"),
    ("Had a very busy day, but ended it feeling proud of what I accomplished", "good"),
    ("Had a falling out with a colleague, which left me feeling upset", "bad"),
    ("Caught up with old friends, reminisced about good memories", "good"),
    ("Felt overwhelmed by my to-do list, couldn’t focus on anything", "bad"),
    ("Had an enjoyable day of learning new things, felt mentally stimulated", "good"),
    ("Worked late into the night, felt exhausted by the end", "bad"),
    ("Had a relaxing day watching movies, felt comfortable and cozy", "good"),
    ("Spent hours in traffic, couldn’t get anything done", "bad"),
    ("Had a day filled with laughter and fun, felt energized and happy", "good"),
    ("Faced a lot of challenges today, but managed to push through", "good"),
    ("Was distracted all day, couldn’t focus on anything important", "bad"),
    ("Had a lovely dinner with my partner, had meaningful conversations", "good"),
    ("Spent the whole day on a project, but didn’t see the results I hoped for", "bad"),
    ("Had a productive day with lots of progress in all areas of my life", "good"),
    ("Felt emotionally drained after a difficult day of work", "bad"),
    ("Had a successful interview, I’m excited about the opportunity", "good"),
    ("Struggled with negative thoughts all day, felt really down", "bad"),
    (
        "I spent the entire day worrying about deadlines and didn't focus enough on completing my work, leaving me feeling anxious and unproductive",
        "bad",
    ),
    (
        "I had a relaxing bath, watched my favorite show, and took a nap, leaving me feeling completely recharged and ready for the next day",
        "good",
    ),
    (
        "I had to deal with a complicated project at work, which made me feel overwhelmed at first, but I managed to make steady progress and solve some problems",
        "good",
    ),
    (
        "I felt lazy and unmotivated throughout the day, avoided all my responsibilities, and ended up not accomplishing anything productive",
        "bad",
    ),
    (
        "I was able to complete every task on my to-do list, had a productive workday, and felt great at the end of the day",
        "good",
    ),
    (
        "I woke up late and felt exhausted all day, my energy was low, and I had trouble concentrating, making the day feel like a drag",
        "bad",
    ),
    (
        "I enjoyed a long walk in the park with friends, we laughed a lot and caught up, which made me feel happy and refreshed",
        "good",
    ),
    (
        "I missed my morning workout, ate unhealthy food all day, and didn't move much, leaving me feeling sluggish and guilty",
        "bad",
    ),
    (
        "I managed to finish a challenging assignment, which I had been dreading, and felt a great sense of accomplishment by the end of the day",
        "good",
    ),
    (
        "I spent hours stuck in traffic, missed an important meeting, and couldn't focus on work, which made me feel frustrated and unproductive",
        "bad",
    ),
    (
        "I had a fantastic day off with no work to worry about, enjoyed a movie marathon, and relaxed with a cup of tea, feeling recharged",
        "good",
    ),
    (
        "I procrastinated all day, sat in front of my computer without accomplishing anything, and wasted time on social media",
        "bad",
    ),
    (
        "I finished a creative project that I've been working on for weeks, and the feeling of completion was so satisfying that I felt great all day",
        "good",
    ),
    (
        "I had an argument with a friend, and even though I tried to move past it, the tension lingered and made me feel upset throughout the day",
        "bad",
    ),
    (
        "I caught up with family members, had a delicious dinner together, and enjoyed our time talking, which made me feel loved and happy",
        "good",
    ),
    (
        "I couldn't concentrate at work because I was constantly distracted, and by the end of the day, I realized I hadn't completed any tasks",
        "bad",
    ),
    (
        "After organizing my workspace and planning out my tasks, I felt much more focused and productive for the rest of the day",
        "good",
    ),
    (
        "I felt anxious all day, couldn't find a way to relax, and ended up wasting hours trying to calm down but getting nothing done",
        "bad",
    ),
    (
        "I went out with friends for dinner and had a blast, laughing the whole night and feeling energized and connected",
        "good",
    ),
    (
        "I stayed in bed all day, didn’t get any work done, and couldn’t shake the feeling of laziness and regret",
        "bad",
    ),
    (
        "I completed my workout, which was intense but left me feeling stronger and more energized, and the rest of the day went smoothly",
        "good",
    ),
    (
        "I didn’t get enough sleep and spent the whole day yawning, feeling tired, and lacking the energy to be productive",
        "bad",
    ),
    (
        "I had a great brainstorming session with my colleagues, and we came up with some exciting new ideas for our project, leaving me feeling inspired",
        "good",
    ),
    (
        "I had so many things on my mind that I felt overwhelmed, and it became hard to focus on any of them, making the day feel unproductive",
        "bad",
    ),
    (
        "I woke up early, had a productive morning, and completed everything I had planned, leaving me with a sense of accomplishment by lunch",
        "good",
    ),
    (
        "I was late to work, which set the tone for the rest of the day, and I couldn’t catch up on my tasks, feeling disorganized",
        "bad",
    ),
    (
        "I spent the afternoon chatting with an old friend, reminiscing about good times, and it made me feel happy and emotionally refreshed",
        "good",
    ),
    (
        "I felt distracted by everything around me, could not concentrate, and by the end of the day, I hadn’t completed any important tasks",
        "bad",
    ),
    (
        "I had a successful and productive day at work, nailed every meeting, and even got ahead of schedule, which made me feel great",
        "good",
    ),
    (
        "I felt mentally drained all day, struggled to keep up with my responsibilities, and ended up accomplishing little, feeling frustrated",
        "bad",
    ),
    (
        "I finished a personal project I've been working on for months and felt so proud of the results, which made the entire day feel fulfilling",
        "good",
    ),
    (
        "I felt disconnected from everything and everyone, couldn’t focus on work, and spent the day in a state of mental fog",
        "bad",
    ),
    (
        "I had a smooth day at work with no interruptions, made great progress, and felt satisfied when I left the office",
        "good",
    ),
    (
        "I was feeling anxious about an upcoming event all day, couldn’t focus on my work, and just couldn't shake the worry",
        "bad",
    ),
    (
        "I enjoyed a cozy evening at home with a good book and a cup of tea, felt peaceful and relaxed after a busy week",
        "good",
    ),
    (
        "I couldn’t stop overthinking, and it made the entire day feel exhausting, I felt mentally exhausted by the end of it",
        "bad",
    ),
    (
        "I had a productive meeting, tackled difficult tasks, and felt energized by my accomplishments, making it a successful day overall",
        "good",
    ),
    (
        "I couldn’t focus on my work, everything felt overwhelming, and I found myself falling behind on deadlines, which made me feel stressed",
        "bad",
    ),
    (
        "I spent a quiet day at home, catching up on tasks I had been putting off, and it felt so rewarding to get things done",
        "good",
    ),
    (
        "I felt incredibly lazy all day, avoided everything I was supposed to do, and ended up with a feeling of guilt and frustration",
        "bad",
    ),
    (
        "I spent time with my family, played games, and had meaningful conversations that brought joy and positivity into my day",
        "good",
    ),
    (
        "I didn’t sleep well, woke up late, and couldn’t catch up on my to-do list, leaving me feeling behind and anxious all day",
        "bad",
    ),
    (
        "I took care of some personal tasks I had been putting off, and finishing them made me feel accomplished and less stressed",
        "good",
    ),
    (
        "I didn’t take a break during work and felt mentally drained by the end of the day, struggling to finish my tasks",
        "bad",
    ),
    (
        "I spent the day doing things I enjoy, cooking, reading, and spending time with loved ones, which made me feel refreshed and content",
        "good",
    ),
    (
        "I was constantly interrupted at work and couldn’t get anything meaningful done, which left me feeling frustrated and unproductive",
        "bad",
    ),
    (
        "I finished all the work I set out to do, and had time left over to relax and unwind, leaving me feeling balanced and accomplished",
        "good",
    ),
    (
        "I kept procrastinating all day, avoided work, and didn’t get anything done, which made me feel like I wasted my time",
        "bad",
    ),
    (
        "I completed a tough project at work, solved some complex problems, and received positive feedback, making the day feel rewarding",
        "good",
    ),
    (
        "I felt unmotivated, couldn’t focus, and kept putting things off, leading to a frustrating and unproductive day",
        "bad",
    ),
    (
        "I got a lot done during the morning, spent the afternoon catching up with friends, and ended the day feeling happy and accomplished",
        "good",
    ),
    (
        "I felt stressed out by the never-ending pile of work, struggled to keep up, and finished the day feeling overwhelmed and exhausted",
        "bad",
    ),
    (
        "I enjoyed a long walk outside, enjoyed the fresh air, and felt mentally recharged for the rest of the day",
        "good",
    ),
    (
        "I had a productive and successful day at work, with everything falling into place, leaving me with a sense of achievement",
        "good",
    ),
    (
        "I found it hard to focus all day, kept getting distracted, and struggled to finish even basic tasks, leaving me feeling unproductive",
        "bad",
    ),
    (
        "I had a peaceful morning, enjoyed some self-care, and tackled my tasks efficiently, which made the rest of the day smooth and enjoyable",
        "good",
    ),
    (
        "I kept pushing back tasks, couldn’t get started, and by the end of the day, nothing had been accomplished",
        "bad",
    ),
    (
        "I had a great conversation with a friend and spent some quality time together, which made me feel happy and fulfilled",
        "good",
    ),
    (
        "I tried to work but couldn’t concentrate and ended up feeling disappointed and frustrated by the lack of productivity",
        "bad",
    ),
    (
        "I spent some time learning new skills and felt really productive, plus it gave me a sense of accomplishment and progress",
        "good",
    ),
    (
        "I had a lot on my plate and felt overwhelmed, couldn’t manage everything and ended up feeling mentally exhausted and stressed",
        "bad",
    ),
    (
        "I had a productive day at work, checked off everything on my to-do list, and rewarded myself with a relaxing evening",
        "good",
    ),
    (
        "I couldn’t focus on work, kept procrastinating, and ended the day with a sense of guilt and frustration",
        "bad",
    ),
    (
        "I had a peaceful and relaxing day, spent time with my loved ones, and felt grateful for the small joys in life",
        "good",
    ),
    (
        "I felt mentally drained, couldn’t concentrate on my tasks, and ended up wasting the entire day",
        "bad",
    ),
    (
        "I spent the day working on my personal projects and making progress, which left me feeling proud and motivated",
        "good",
    ),
    (
        "I stayed up late and woke up tired, spent the whole day struggling to stay awake and not accomplishing anything",
        "bad",
    ),
    (
        "I got some unexpected good news, which lifted my spirits and made me feel positive throughout the day",
        "good",
    ),
    (
        "I spent the entire day feeling stressed, worrying about work deadlines, and ended up feeling physically and mentally drained",
        "bad",
    ),
    (
        "I had a really productive day, crossed off everything on my to-do list, and even had some free time to relax",
        "good",
    ),
    (
        "I felt completely unmotivated, couldn’t focus on my tasks, and spent the day watching TV instead of getting anything done",
        "bad",
    ),
    (
        "I spent time with close friends, laughed a lot, and shared good memories, which made me feel grateful and content",
        "good",
    ),
    (
        "I was stuck in meetings all day and couldn’t get any actual work done, which left me feeling frustrated and overwhelmed",
        "bad",
    ),
    (
        "I made significant progress on a big project, solved a lot of problems, and felt really satisfied by the end of the day",
        "good",
    ),
    (
        "I was feeling overwhelmed and couldn’t keep up with my responsibilities, which made me feel behind and stressed all day",
        "bad",
    ),
    (
        "I got up early, worked efficiently, and had a sense of accomplishment by midday, followed by a relaxing afternoon",
        "good",
    ),
    (
        "I spent too much time worrying about things that didn’t matter, which made the day drag on and left me feeling unproductive",
        "bad",
    ),
    (
        "I had a productive day, worked on a new project, and by the evening, I felt accomplished and motivated to keep going",
        "good",
    ),
    (
        "I couldn’t focus on anything today, got distracted by small things, and ended the day with a long list of unfinished tasks",
        "bad",
    ),
    (
        "I had a productive morning, met some new people, and spent the afternoon relaxing, making the day feel balanced and enjoyable",
        "good",
    ),
    (
        "I wasted too much time on non-essential tasks, couldn’t get focused, and ended the day feeling unaccomplished and frustrated",
        "bad",
    ),
    (
        "I completed a personal goal I set for the day, made significant progress, and felt really good about my achievements",
        "good",
    ),
    (
        "I felt mentally overwhelmed, couldn’t focus, and ended up procrastinating all day, leaving me feeling unproductive",
        "bad",
    ),
]
